name = "MaxwellWave"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MaxwellWave", "PlasmaEquations", "NavierStokes"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "3d425859e73fcfbef85b9638c2a91708ef4a22d4"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "dc1e7a305e4976270e0ca593f952d755da502b12"

[[lean_lib]]
name = "MaxwellWave"

[[lean_lib]]
name = "PlasmaEquations"

[[lean_lib]]
name = "NavierStokes"

[[lean_lib]]
name = "MatlibDraft"
